assert_valid_technology_type_ai <-
  function(x, any.missing = FALSE, .var.name = checkmate::vname(x), add = NULL) {
    allowed_strings <-
      c(
        "Biogas",
        "Biomass",
        "Bulk Carrier",
        "Bus Chassis",
        "CBM",
        "Chemical Tanker",
        "Container",
        "Conventional Gas",
        "Conventional NGL",
        "Conventional Oil",
        "Cruise",
        "Deepwater Gas",
        "Deepwater NGL",
        "Deepwater Oil",
        "Dry With Preheater And Precalciner",
        "Dry Without Preheater (Long Dry Kiln)",
        "Ferry-Pax Only",
        "Ferry-RoPax",
        "Full-sized Light Truck",
        "General Cargo",
        "Geothermal",
        "Heavy Freight Transport",
        "Heavy Oil",
        "Integrated Blast Furnace",
        "Integrated DRI Furnace",
        "Integrated Open Hearth Furnace",
        "Liquefied Gas Tanker",
        "Long-Haul",
        "Luxury/Sports Car",
        "Medium Car",
        "Medium Freight Transport",
        "Medium-Haul",
        "Mid-sized Light Truck",
        "Mini-Mill",
        "Mixed Kiln Type",
        "Motor Home Chassis",
        "Ocean",
        "Oil Sands",
        "Oil Tanker",
        "Other Liquids Tanker",
        "Refrigerated Bulk",
        "Ro-Ro",
        "Semi-Wet/Semi Dry",
        "Short-Haul",
        "Small Car",
        "Small Light Truck",
        "Solar CPV",
        "Solar CSP",
        "Solar PV",
        "Surface",
        "Surface and Underground",
        "Unconventional Gas",
        "Unconventional NGL",
        "Unconventional Oil",
        "Underground",
        "Wet / Shaft Kiln",
        "Wind Offshore",
        "Wind Onshore"
      )

    msg <- "must contain only valid technology_type names, but has additional element{?s} {.val {misses}}"

    assert_subset(
      x = x,
      choices = allowed_strings,
      msg = msg,
      any.missing = any.missing,
      .var.name = .var.name,
      add = add
    )
  }
